// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgcZPE-eudKVY2SsXi1NTLPLuO4PvGABw',
    appId: '1:734661286117:web:0baecbd144126b7fbfdc0c',
    messagingSenderId: '734661286117',
    projectId: 'running-coach-app-ef243',
    authDomain: 'running-coach-app-ef243.firebaseapp.com',
    storageBucket: 'running-coach-app-ef243.firebasestorage.app',
    measurementId: 'G-LCJVZNR3GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMfUdwi_5zbWJFmmVMJdtXBMuQ3XLji-E',
    appId: '1:734661286117:android:6f7994ec0147a076bfdc0c',
    messagingSenderId: '734661286117',
    projectId: 'running-coach-app-ef243',
    storageBucket: 'running-coach-app-ef243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIecEf5vAX6qD0HK4C-LUqBFN0cdVHjWw',
    appId: '1:734661286117:ios:5fce89a60682bfd2bfdc0c',
    messagingSenderId: '734661286117',
    projectId: 'running-coach-app-ef243',
    storageBucket: 'running-coach-app-ef243.firebasestorage.app',
    iosBundleId: 'com.example.runningCoachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIecEf5vAX6qD0HK4C-LUqBFN0cdVHjWw',
    appId: '1:734661286117:ios:5fce89a60682bfd2bfdc0c',
    messagingSenderId: '734661286117',
    projectId: 'running-coach-app-ef243',
    storageBucket: 'running-coach-app-ef243.firebasestorage.app',
    iosBundleId: 'com.example.runningCoachApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgcZPE-eudKVY2SsXi1NTLPLuO4PvGABw',
    appId: '1:734661286117:web:4d01a846e7774acebfdc0c',
    messagingSenderId: '734661286117',
    projectId: 'running-coach-app-ef243',
    authDomain: 'running-coach-app-ef243.firebaseapp.com',
    storageBucket: 'running-coach-app-ef243.firebasestorage.app',
    measurementId: 'G-L0ZSF8BDH3',
  );

}